name: Shitpost GPT Naval

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,18 * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: npm ci
    - run: npm start shitpost-gptnaval
