name: Shitpost Pomp

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 0,5,10,15 * * *'
  workflow_dispatch:
jobs:
  shitpost:
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: npm ci
    - run: npm start shitpost-pomp
